use sha256 sum
FreeCAD/freecad-feedstock pull request #20
Opened 2024-12-29 15:18 UTC by looooo

2024-12-29 15:19 UTC, looooo commented
@adrianinsaval 
depends on https://github.com/FreeCAD/FreeCAD-Bundle/pull/362

2024-12-30 18:51 UTC, oursland commented
I'll re-run the failed checks after post-merge build of [https://github.com/FreeCAD/FreeCAD-Bundle/pull/362](https://github.com/FreeCAD/FreeCAD-Bundle/actions/runs/12550638791) completes.

2024-12-30 22:32 UTC, oursland commented
@looooo It appears there's a Jinja expansion error due to `build_number` somehow being set to the `sha256` value in `meta.yaml`.

2024-12-31 03:41 UTC, adrianinsaval requested changes

2024-12-31 03:41 UTC, adrianinsaval commented on recipe/increase_build_number.py
> +url = "https://github.com/FreeCAD/FreeCAD-Bundle/releases/download/weekly-builds/freecad_source_sha256sum.txt"
```suggestion
url = "https://github.com/FreeCAD/FreeCAD-Bundle/releases/download/weekly-builds/freecad_source.tar.gz-SHA256.txt"
```

sorry I changed the name to match the rest of the SHA256.txt files we have when I fixed the source package action

2024-12-31 03:41 UTC, adrianinsaval commented on recipe/increase_build_number.py
> +text = re.sub(r"(?<={% set sha256 = )\d+", str(sha256), text)
I think this regex here is not correct as it is searching for digits only while the sha256sum also has letters

2024-12-31 03:48 UTC, adrianinsaval commented on recipe/meta.yaml
> +{% set sha256 = 65dc32f217a3fe757f5b81bb45dae0cc151c82304e8016ddcc9efbd46fbbc864 %}
```suggestion
{% set sha256 = "65dc32f217a3fe757f5b81bb45dae0cc151c82304e8016ddcc9efbd46fbbc864" %}
```

ci failure says

> expected token 'end of statement block', got 'dc32f217a3fe757f5b81bb45dae0cc151c82304e8016ddcc9efbd46fbbc864'

which leads me to believe it is trying to take it as a number since the error starts with the first letter

2024-12-31 11:35 UTC, looooo commented
sry didn't want to trigger ci's.

2025-02-25 07:50 UTC, maxwxyz commented
is this still relevant? All mentioned PRs are merged.

2025-02-25 11:40 UTC, closed without merging